import os

class ReportGenerator:
    """
    Generates HTML-based recruiter reports for individual players and squad comparisons.
    Uses pure Python string formatting for maximum portability.
    """
    def __init__(self, aggregator, comparator):
        self.aggregator = aggregator
        self.comparator = comparator
        self.css = """
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: 0 auto; padding: 20px; background: #f4f7f6; }
        .card { background: white; border-radius: 8px; padding: 25px; margin-bottom: 25px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1, h2, h3 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #3498db; color: white; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .badge { display: inline-block; padding: 5px 12px; border-radius: 20px; font-size: 0.85em; font-weight: bold; margin-right: 5px; margin-bottom: 5px; }
        .badge-green { background: #2ecc71; color: white; }
        .badge-red { background: #e74c3c; color: white; }
        .badge-blue { background: #3498db; color: white; }
        .winner { background-color: #d4edda !important; font-weight: bold; }
        .footer { text-align: center; margin-top: 50px; font-size: 0.9em; color: #7f8c8d; }
        .metrics-grid { display: flex; gap: 20px; flex-wrap: wrap; }
        .metric-item { flex: 1; min-width: 200px; background: #ecf0f1; padding: 15px; border-radius: 5px; text-align: center; }
        .metric-value { font-size: 1.8em; font-weight: bold; color: #2980b9; }
        """

    def _get_badge_class(self, flag):
        positive = ['elite', 'high_jumper', 'pro', 'normalised']
        for p in positive:
            if p in flag.lower(): return "badge-green"
        return "badge-red"

    def generate_player_report(self, track_id: str, output_dir: str = 'data/reports/') -> str:
        os.makedirs(output_dir, exist_ok=True)
        p = self.aggregator.get_player_profile(track_id)
        if not p: return "Player not found"

        bio = p.get('biomechanics', {})
        flags_html = "".join([f'<span class="badge {self._get_badge_class(f)}">{f}</span>' for f in p.get('recruiter_flags', [])])
        notes_html = "".join([f"<li>{n}</li>" for n in p.get('scoring_notes', [])])

        html = f"""
        <html>
        <head><style>{self.css}</style></head>
        <body>
            <h1>Volleyball Recruiter Report — Player {track_id}</h1>
            
            <div class="card">
                <h2>Athlete Summary</h2>
                <div class="metrics-grid">
                    <div class="metric-item"><div>Role</div><div class="metric-value">{p.get('role', 'N/A').upper()}</div></div>
                    <div class="metric-item"><div>FIVB Score</div><div class="metric-value">{round(p.get('fivb_score', 0), 1)}</div></div>
                    <div class="metric-item"><div>Frames Analysed</div><div class="metric-value">{p.get('total_frames_analysed', 0)}</div></div>
                </div>
                <div style="margin-top:20px;">{flags_html}</div>
            </div>

            <div class="card">
                <h2>Biomechanical Performance</h2>
                <table>
                    <tr><th>Metric</th><th>Value</th><th>FIVB Benchmark</th></tr>
                    <tr><td>Arm Cock Angle</td><td>{round(bio.get('arm_cock_angle', 0), 1)}°</td><td>150° - 180° (Ideal)</td></tr>
                    <tr><td>Jump Height (Norm)</td><td>{round(bio.get('jump_height_normalised', 0), 3)}</td><td>> 0.35 (Elite)</td></tr>
                    <tr><td>Spike Events</td><td>{p.get('total_spike_events', 0)}</td><td>> 5 (Statistically Significant)</td></tr>
                    <tr><td>Jump Events</td><td>{p.get('total_jump_events', 0)}</td><td>> 5 (Statistically Significant)</td></tr>
                </table>
            </div>

            <div class="card">
                <h2>Scoring Notes & Caveats</h2>
                <ul>{notes_html or "<li>No specific caveats detected.</li>"}</ul>
            </div>

            <div class="footer">Generated by Elite Volleyball Biomechanics AI — {p.get('video_id', 'Batch Process')}</div>
        </body>
        </html>
        """
        
        path = os.path.join(output_dir, f"{track_id}_report.html")
        with open(path, 'w') as f:
            f.write(html)
        return path

    def generate_comparison_report(self, track_id_a: str, track_id_b: str, output_dir: str = 'data/reports/') -> str:
        os.makedirs(output_dir, exist_ok=True)
        res = self.comparator.compare(track_id_a, track_id_b)
        if "error" in res: return res["error"]

        rows = ""
        for label, m in res["metrics"].items():
            win_a = "winner" if m["winner"] == track_id_a else ""
            win_b = "winner" if m["winner"] == track_id_b else ""
            rows += f"<tr><td>{label.replace('_', ' ').title()}</td><td class='{win_a}'>{m['a']}</td><td class='{win_b}'>{m['b']}</td></tr>"

        html = f"""
        <html>
        <head><style>{self.css}</style></head>
        <body>
            <h1>Athlete Comparison: {track_id_a} vs {track_id_b}</h1>
            
            <div class="card">
                <h2>Metric Head-to-Head</h2>
                <table>
                    <tr><th>Metric</th><th>Player {track_id_a}</th><th>Player {track_id_b}</th></tr>
                    {rows}
                </table>
            </div>

            <div class="card">
                <h2>Analysis Recommendation</h2>
                <p><strong>Overall Verdict:</strong> {res['recommendation']}</p>
                <div class="metrics-grid">
                    <div style="flex:1;">
                        <h3>Advantages for {track_id_a}</h3>
                        <ul>{"".join([f"<li>{a}</li>" for a in res['advantages_a']]) or "<li>None significant</li>"}</ul>
                    </div>
                    <div style="flex:1;">
                        <h3>Advantages for {track_id_b}</h3>
                        <ul>{"".join([f"<li>{a}</li>" for a in res['advantages_b']]) or "<li>None significant</li>"}</ul>
                    </div>
                </div>
            </div>

            <div class="footer">Generated by Elite Volleyball Biomechanics AI</div>
        </body>
        </html>
        """
        
        path = os.path.join(output_dir, f"{track_id_a}_vs_{track_id_b}_report.html")
        with open(path, 'w') as f:
            f.write(html)
        return path

    def generate_squad_ranking(self, role: str = None, top_n: int = 10, output_dir: str = 'data/reports/') -> str:
        os.makedirs(output_dir, exist_ok=True)
        ranked = self.aggregator.rank_players(role=role, top_n=top_n)
        
        rows = ""
        for i, p in enumerate(ranked):
            flags = " ".join([f'<span class="badge badge-blue">{f}</span>' for f in p.get('recruiter_flags', [])[:3]])
            rows += f"<tr><td>{i+1}</td><td>{p['track_id']}</td><td>{p['role']}</td><td>{p['fivb_score']}</td><td>{flags}</td></tr>"

        html = f"""
        <html>
        <head><style>{self.css}</style></head>
        <body>
            <h1>Squad Ranking — {role.upper() if role else 'All Positions'}</h1>
            <div class="card">
                <table>
                    <tr><th>Rank</th><th>Track ID</th><th>Role</th><th>FIVB Score</th><th>Top Flags</th></tr>
                    {rows}
                </table>
            </div>
            <div class="footer">Generated by Elite Volleyball Biomechanics AI</div>
        </body>
        </html>
        """
        
        path = os.path.join(output_dir, f"squad_ranking_{role or 'all'}.html")
        with open(path, 'w') as f:
            f.write(html)
        return path
